# Generated by Django 3.2.8 on 2021-10-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_auto_20211021_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attrubutes',
        ),
    ]
