# Generated by Django 3.2.8 on 2021-10-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_category_description'),
        ('product_management', '0002_auto_20211008_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='blog-images'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=10),
        ),
    ]
