# Generated by Django 3.2.8 on 2021-10-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20211021_1521'),
        ('product_management', '0003_remove_product_attrubutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='attrubute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attrubute', to='masters.attribute'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_management.product'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrubute_variant', to='masters.attributevalue'),
        ),
    ]
