# Generated by Django 3.2.8 on 2021-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_auto_20211008_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0, max_length=2),
        ),
    ]
