# Generated by Django 3.2.8 on 2021-10-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
