# Generated by Django 3.2.8 on 2021-10-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
