# Generated by Django 3.2.8 on 2021-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_attribute_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True),
        ),
    ]
